// src/utils/utcOffsets.ts

/**
 * Baza krajów i odpowiadających im offsetów UTC
 * ⚠️ Offsety w godzinach, mogą zawierać wartości półgodzinne (np. 5.5)
 */
export const countryToUTCOffset: Record<string, number> = {
  "Afghanistan": 4.5,
  "Albania": 1,
  "Algeria": 1,
  "Andorra": 1,
  "Angola": 1,
  "Argentina": -3,
  "Armenia": 4,
  "Australia (Sydney)": 10,
  "Australia (Perth)": 8,
  "Austria": 1,
  "Azerbaijan": 4,
  "Bahamas": -5,
  "Bahrain": 3,
  "Bangladesh": 6,
  "Belarus": 3,
  "Belgium": 1,
  "Belize": -6,
  "Benin": 1,
  "Bhutan": 6,
  "Bolivia": -4,
  "Bosnia & Herzegovina": 1,
  "Botswana": 2,
  "Brazil (Brasilia)": -3,
  "Brazil (Manaus)": -4,
  "Brazil (Fernando de Noronha)": -2,
  "Brunei": 8,
  "Bulgaria": 2,
  "Burundi": 2,
  "Cambodia": 7,
  "Cameroon": 1,
  "Canada (EST)": -5,
  "Canada (CST)": -6,
  "Canada (MST)": -7,
  "Canada (PST)": -8,
  "Canada (Newfoundland)": -3.5,
  "Chile": -4,
  "China": 8,
  "Colombia": -5,
  "Costa Rica": -6,
  "Croatia": 1,
  "Cuba": -5,
  "Cyprus": 2,
  "Czech Republic": 1,
  "Denmark": 1,
  "Djibouti": 3,
  "Dominican Republic": -4,
  "Ecuador": -5,
  "Egypt": 2,
  "El Salvador": -6,
  "Estonia": 2,
  "Ethiopia": 3,
  "Fiji": 12,
  "Finland": 2,
  "France": 1,
  "Gabon": 1,
  "Gambia": 0,
  "Georgia": 4,
  "Germany": 1,
  "Ghana": 0,
  "Greece": 2,
  "Guatemala": -6,
  "Guinea": 0,
  "Honduras": -6,
  "Hong Kong": 8,
  "Hungary": 1,
  "Iceland": 0,
  "India": 5.5,
  "Indonesia (Jakarta)": 7,
  "Indonesia (Bali)": 8,
  "Indonesia (Papua)": 9,
  "Iran": 3.5,
  "Iraq": 3,
  "Ireland": 0,
  "Israel": 2,
  "Italy": 1,
  "Jamaica": -5,
  "Japan": 9,
  "Jordan": 2,
  "Kazakhstan (Almaty)": 6,
  "Kazakhstan (Nur-Sultan)": 5,
  "Kenya": 3,
  "Kuwait": 3,
  "Kyrgyzstan": 6,
  "Laos": 7,
  "Latvia": 2,
  "Lebanon": 2,
  "Lesotho": 2,
  "Liberia": 0,
  "Libya": 2,
  "Liechtenstein": 1,
  "Lithuania": 2,
  "Luxembourg": 1,
  "Madagascar": 3,
  "Malawi": 2,
  "Malaysia": 8,
  "Maldives": 5,
  "Mali": 0,
  "Malta": 1,
  "Mauritius": 4,
  "Mexico (Central)": -6,
  "Mexico (Pacific)": -8,
  "Mexico (Eastern)": -5,
  "Moldova": 2,
  "Monaco": 1,
  "Mongolia": 8,
  "Montenegro": 1,
  "Morocco": 1,
  "Mozambique": 2,
  "Myanmar": 6.5,
  "Namibia": 2,
  "Nepal": 5.75,
  "Netherlands": 1,
  "New Zealand": 12,
  "Nicaragua": -6,
  "Niger": 1,
  "Nigeria": 1,
  "North Korea": 9,
  "Norway": 1,
  "Oman": 4,
  "Pakistan": 5,
  "Panama": -5,
  "Papua New Guinea": 10,
  "Paraguay": -4,
  "Peru": -5,
  "Philippines": 8,
  "Poland": 1,
  "Portugal": 0,
  "Qatar": 3,
  "Romania": 2,
  "Russia (Moscow)": 3,
  "Russia (Novosibirsk)": 7,
  "Russia (Vladivostok)": 10,
  "Saudi Arabia": 3,
  "Senegal": 0,
  "Serbia": 1,
  "Singapore": 8,
  "Slovakia": 1,
  "Slovenia": 1,
  "South Africa": 2,
  "South Korea": 9,
  "Spain": 1,
  "Sri Lanka": 5.5,
  "Sudan": 2,
  "Sweden": 1,
  "Switzerland": 1,
  "Syria": 2,
  "Taiwan": 8,
  "Tajikistan": 5,
  "Tanzania": 3,
  "Thailand": 7,
  "Togo": 0,
  "Tunisia": 1,
  "Turkey": 3,
  "Turkmenistan": 5,
  "Uganda": 3,
  "Ukraine": 2,
  "United Arab Emirates": 4,
  "United Kingdom": 0,
  "United States (EST)": -5,
  "United States (CST)": -6,
  "United States (MST)": -7,
  "United States (PST)": -8,
  "Uruguay": -3,
  "Uzbekistan": 5,
  "Vanuatu": 11,
  "Venezuela": -4,
  "Vietnam": 7,
  "Yemen": 3,
  "Zambia": 2,
  "Zimbabwe": 2
};